name: Update Tweet Gist

on:
  workflow_dispatch:       # allows manual run
  schedule:
    - cron: '0 * * * *'     # every hour

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch user ID, latest tweet, and update gist
        run: |
          echo "🔍 Getting user ID for @BWBaseball_Mtka"
          curl -s -X GET "https://api.twitter.com/2/users/by/username/BWBaseball_Mtka" \
            -H "Authorization: Bearer ${{ secrets.TWITTER_BEARER_TOKEN }}" > user.json

          USER_ID=$(jq -r '.data.id' user.json)
          echo "✅ Fetched user ID: $USER_ID"

          echo "📦 Fetching latest tweet for user ID: $USER_ID"
          curl -s -X GET "https://api.twitter.com/2/users/$USER_ID/tweets?max_results=5&exclude=retweets,replies&tweet.fields=created_at" \
            -H "Authorization: Bearer ${{ secrets.TWITTER_BEARER_TOKEN }}" > tweets.json

          echo "===== RAW RESPONSE FROM TWITTER ====="
          cat tweets.json
          echo "====================================="

          # Check if rate-limited
          STATUS=$(jq -r '.status // empty' tweets.json)
          if [ "$STATUS" = "429" ]; then
            echo "❌ Rate limited by Twitter API. Skipping update."
            exit 0
          fi

          TWEET_ID=$(jq -r '.data[0].id' tweets.json)
          echo "🆔 Latest tweet ID: $TWEET_ID"

          if [ "$TWEET_ID" = "null" ] || [ -z "$TWEET_ID" ]; then
            echo "⚠️ No tweet ID found. Skipping update."
            exit 0
          fi

          echo "{ \"url\": \"https://twitter.com/BWBaseball_Mtka/status/$TWEET_ID\" }" > latest-tweet.json

          echo "✏️ Updating Gist..."
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GIST_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$(cat latest-tweet.json)" '{"files": {"latest-tweet.json": {"content": $content}}}')" \
            https://api.github.com/gists/8359cfb1d50d98fcefe7b1e8585087c2

          echo "✅ Done."
